runtime: nodejs20
env: standard

instance_class: F1

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

  - url: /assets
    static_dir: dist/assets
    secure: always

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: automatic

env_variables:
  NODE_ENV: "production"